# Generated by Django 3.1.7 on 2021-05-19 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210519_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='A_1_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='A_2A_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='A_2B_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='A_3A_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='A_3B_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_1_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_2A_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_2B_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_3A_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_3B_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_3C_qty_fwd_nurse',
        ),
        migrations.RemoveField(
            model_name='cardiacsupplied',
            name='B_3D_qty_fwd_nurse',
        ),
        migrations.AlterField(
            model_name='requests',
            name='dateofprocedure',
            field=models.DateField(default=datetime.date(2021, 5, 20)),
        ),
    ]
