# Generated by Django 3.1.7 on 2021-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_1_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_2A_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_2B_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_3A_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_3B_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_3C_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacrequested',
            name='B_3D_qty',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_1_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_1_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_2A_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_2A_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_2B_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_2B_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_3A_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_3A_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_3B_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_3B_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_1_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_1_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_2A_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_2A_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_2B_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_2B_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3A_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3A_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3B_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3B_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3C_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3C_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3D_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3D_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requests',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requests',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
