# Generated by Django 3.1.7 on 2021-04-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210418_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_1_name',
            new_name='A_1_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_2A_name',
            new_name='A_2A_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_2B_name',
            new_name='A_2B_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_3A_name',
            new_name='A_3A_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_3B_name',
            new_name='A_3B_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_1_name',
            new_name='B_1_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_2A_name',
            new_name='B_2A_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_2B_name',
            new_name='B_2B_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3A_name',
            new_name='B_3A_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3B_name',
            new_name='B_3B_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3C_name',
            new_name='B_3C_qty_rcd',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3D_name',
            new_name='B_3D_qty_rcd',
        ),
    ]
