# Generated by Django 3.1.7 on 2021-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210418_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='notificationbit',
            field=models.BooleanField(default=False),
        ),
    ]
