# Generated by Django 3.1.7 on 2021-04-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210429_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_1_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_2A_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_2B_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_3A_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='A_3B_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_1_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_2A_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_2B_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3A_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3B_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3C_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardiacsupplied',
            name='B_3D_qty_rcd',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
