# Generated by Django 3.1.7 on 2021-05-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210515_2259'),
        ('api', '0012_requests_dateofprocedure'),
    ]

    operations = [
    ]
