# Generated by Django 3.1.7 on 2021-05-16 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20210516_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_1_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_1_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2A_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2A_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2B_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2B_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3A_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3A_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3B_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3B_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_1_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_1_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2A_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2A_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2B_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2B_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3A_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3A_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3B_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3B_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3C_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3C_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3D_tally_nurse',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3D_tally_unitman',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='requests',
            name='dateofprocedure',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
    ]
