# Generated by Django 3.1.7 on 2021-05-19 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20210516_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_1_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_1_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2A_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2A_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2B_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_2B_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3A_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3A_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3B_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='A_3B_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_1_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_1_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2A_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2A_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2B_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_2B_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3A_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3A_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3B_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3B_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3C_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3C_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3D_consumed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cardiacsupplied',
            name='B_3D_qty_rcd_nurse',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='dateofprocedure',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='state',
            field=models.CharField(default='Filling', max_length=100),
        ),
    ]
