# Generated by Django 3.1.7 on 2021-05-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210519_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_1_qty_rcd_nurse',
            new_name='A_1_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_2A_qty_rcd_nurse',
            new_name='A_2A_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_2B_qty_rcd_nurse',
            new_name='A_2B_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_3A_qty_rcd_nurse',
            new_name='A_3A_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='A_3B_qty_rcd_nurse',
            new_name='A_3B_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_1_qty_rcd_nurse',
            new_name='B_1_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_2A_qty_rcd_nurse',
            new_name='B_2A_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_2B_qty_rcd_nurse',
            new_name='B_2B_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3A_qty_rcd_nurse',
            new_name='B_3A_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3B_qty_rcd_nurse',
            new_name='B_3B_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3C_qty_rcd_nurse',
            new_name='B_3C_qty_fwd_nurse',
        ),
        migrations.RenameField(
            model_name='cardiacsupplied',
            old_name='B_3D_qty_rcd_nurse',
            new_name='B_3D_qty_fwd_nurse',
        ),
    ]
