from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime
# Create your models here.

#class Users(models.Model):
#    username = models.CharField(max_length=100,primary_key=True,null=False,default='yo')
#    name = models.CharField(max_length=100,null=False,default='name')
#    password = models.CharField(max_length=100,null=False,default='password')
#    category = models.CharField(max_length=100,default='Nurse')
    # def __str__(self):
    #     return self.username


class Requests(models.Model):
    crnumber = models.CharField(max_length=100,default="_")
    wardadhaar = models.IntegerField(validators=[MinValueValidator(100000000000),MaxValueValidator(999999999999)])
    patientname = models.CharField(max_length=100,default="Patient")
    docnumber = models.CharField(max_length=100,null=False,primary_key=True)
    createdby = models.CharField(max_length=100,default='admin')
    createdat = models.DateTimeField(auto_now_add=True)
    department = models.CharField(max_length=100,default='default-department')
    consultantuname = models.CharField(max_length=100)
    bsa = models.FloatField()
    height = models.IntegerField()
    weight = models.IntegerField()
    
    nurseflag = models.CharField(max_length=1,default='F')
    perfusionistflag = models.CharField(max_length=1,default='T')
    doctorflag = models.CharField(max_length=1,default='F')
    technicianflag = models.CharField(max_length=1,default='T')
    consultantflag = models.CharField(max_length=1,default='F')
    state = models.CharField(max_length=100,default="Filling")
    remarksfromconsultant = models.CharField(max_length=500,default="",blank=True)
    notificationbit = models.BooleanField(default=False)
    dateofprocedure = models.DateField(default=datetime.date.today())

#doubt on number of fields, dictionary coz each item has many features..e.g. brand, quantity

# class CardiacReceived(models.Model):
#     docnumber = models.CharField(max_length=100,null=False,primary_key=True)
#     quantity = models.
#      {'sdfs':12, 'sdfsdf',}

# class Anesthetic:
#     brand:
#     size:  
# # # make trigger to check, allreceived 
# # #if allrec.. = True , delete the request table entry
# class CardiacRequested(models.Model):
#     super CardiacReceived  
#     allreceived = models.BooleanField(default=False)

class Patient(models.Model): 
    name = models.CharField(max_length=100)
    wardadhaar = models.IntegerField(primary_key=True,validators=[MinValueValidator(100000000000),MaxValueValidator(999999999999)])
    bloodgroup = models.CharField(max_length=50)
    gender = models.CharField(max_length=100)
    dob =  models.DateField(null=False)

class UserManager(BaseUserManager):
    use_in_migrations = True
    def create_user(self, username, name, category, password=None):
        user = self.model(
            username=username,
            category=category,
            name=name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_staffuser(self, email, name, date_of_birth, password):
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,         
            name=name,
        )
        user.staff = True
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, name, category, password):
        user = self.create_user(
            username=username,
            category=category,
            name="True",
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class User(AbstractUser):
    # username = models.CharField(max_length=100,primary_key=True,null=False,default='yo')
    # name = models.CharField(max_length=100,null=False,default='name')
    category = models.CharField(max_length=100,default='Nurse')
    # objects = UserManager()

    # USERNAME_FIELD = 'username'
    # REQUIRED_FIELDS = [ 'category','name' ]

    def __str__(self):              # __unicode__ on Python 2
        return self.username

class CardiacSupplied(models.Model):
    docnumber = models.CharField(max_length=100,primary_key=True,default="_")
    A_1_qty_rcd = models.CharField(max_length=500,default='0')
    A_1_descr = models.CharField(max_length=500,default='_')
    A_1_brand = models.CharField(max_length=500,default='_')
    A_1_qty = models.IntegerField()
    A_1_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    A_1_tally_unitman = models.CharField(max_length=1,default='F')
    A_1_tally_nurse = models.CharField(max_length=1,default='F')
    
    A_2A_qty_rcd = models.CharField(max_length=500,default='0')
    A_2A_descr = models.CharField(max_length=500,default='_')
    A_2A_brand = models.CharField(max_length=500,default='_')
    A_2A_qty = models.IntegerField()
    A_2A_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    A_2A_tally_unitman = models.CharField(max_length=1,default='F')
    A_2A_tally_nurse = models.CharField(max_length=1,default='F')

    A_2B_qty_rcd = models.CharField(max_length=500,default='0')
    A_2B_descr = models.CharField(max_length=500,default='_')
    A_2B_brand = models.CharField(max_length=500,default='_')
    A_2B_qty = models.IntegerField()
    A_2B_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    A_2B_tally_unitman = models.CharField(max_length=1,default='F')
    A_2B_tally_nurse = models.CharField(max_length=1,default='F')

    A_3A_qty_rcd = models.CharField(max_length=500,default='0')
    A_3A_descr = models.CharField(max_length=500,default='_')
    A_3A_brand = models.CharField(max_length=500,default='_')
    A_3A_qty = models.IntegerField()
    A_3A_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    A_3A_tally_unitman = models.CharField(max_length=1,default='F')
    A_3A_tally_nurse = models.CharField(max_length=1,default='F')

    A_3B_qty_rcd = models.CharField(max_length=500,default='0')
    A_3B_descr = models.CharField(max_length=500,default='_')
    A_3B_brand = models.CharField(max_length=500,default='_')
    A_3B_qty = models.IntegerField()
    A_3B_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    A_3B_tally_unitman = models.CharField(max_length=1,default='F')
    A_3B_tally_nurse = models.CharField(max_length=1,default='F')

    A_1_consumed = models.IntegerField()
    A_2A_consumed = models.IntegerField()
    A_2B_consumed = models.IntegerField()
    A_3A_consumed = models.IntegerField()
    A_3B_consumed = models.IntegerField()
    
    B_1_consumed = models.IntegerField()
    B_2A_consumed = models.IntegerField()
    B_2B_consumed = models.IntegerField()
    B_3A_consumed = models.IntegerField()
    B_3B_consumed = models.IntegerField()
    B_3C_consumed = models.IntegerField()
    B_3D_consumed = models.IntegerField()


    B_1_qty_rcd = models.CharField(max_length=500,default='0')
    B_1_descr = models.CharField(max_length=500,default='_')
    B_1_brand = models.CharField(max_length=500,default='_')
    B_1_qty = models.IntegerField()
    B_1_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_1_tally_unitman = models.CharField(max_length=1,default='F')
    B_1_tally_nurse = models.CharField(max_length=1,default='F')
    
    B_2A_qty_rcd = models.CharField(max_length=500,default='0')
    B_2A_descr = models.CharField(max_length=500,default='_')
    B_2A_brand = models.CharField(max_length=500,default='_')
    B_2A_qty = models.IntegerField()
    B_2A_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_2A_tally_unitman = models.CharField(max_length=1,default='F')
    B_2A_tally_nurse = models.CharField(max_length=1,default='F')

    B_2B_qty_rcd = models.CharField(max_length=500,default='0')
    B_2B_descr = models.CharField(max_length=500,default='_')
    B_2B_brand = models.CharField(max_length=500,default='_')
    B_2B_qty = models.IntegerField()
    B_2B_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_2B_tally_unitman = models.CharField(max_length=1,default='F')
    B_2B_tally_nurse = models.CharField(max_length=1,default='F')

    B_3A_qty_rcd = models.CharField(max_length=500,default='0')
    B_3A_descr = models.CharField(max_length=500,default='_')
    B_3A_brand = models.CharField(max_length=500,default='_')
    B_3A_qty = models.IntegerField()
    B_3A_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_3A_tally_unitman = models.CharField(max_length=1,default='F')
    B_3A_tally_nurse = models.CharField(max_length=1,default='F')
    
    B_3B_qty_rcd = models.CharField(max_length=500,default='0')
    B_3B_descr = models.CharField(max_length=500,default='_')
    B_3B_brand = models.CharField(max_length=500,default='_')
    B_3B_qty = models.IntegerField()
    B_3B_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_3B_tally_unitman = models.CharField(max_length=1,default='F')
    B_3B_tally_nurse = models.CharField(max_length=1,default='F')

    B_3C_qty_rcd = models.CharField(max_length=500,default='0')
    B_3C_descr = models.CharField(max_length=500,default='_')
    B_3C_brand = models.CharField(max_length=500,default='_')
    B_3C_qty = models.IntegerField()
    B_3C_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_3C_tally_unitman = models.CharField(max_length=1,default='F')
    B_3C_tally_nurse = models.CharField(max_length=1,default='F')

    B_3D_qty_rcd = models.CharField(max_length=500,default='0')
    B_3D_descr = models.CharField(max_length=500,default='_')
    B_3D_brand = models.CharField(max_length=500,default='_')
    B_3D_qty = models.IntegerField()
    B_3D_qty_fwd_nurse = models.CharField(max_length=100,default='0')
    B_3D_tally_unitman = models.CharField(max_length=1,default='F')
    B_3D_tally_nurse = models.CharField(max_length=1,default='F')

    # A_4_qty_rcd = models.CharField(max_length=500,default='0')
    # A_4_descr = models.CharField(max_length=500,default='_')
    # A_4_brand = models.CharField(max_length=500,default='_')
    # A_4_qty = models.IntegerField()
    # A_5_qty_rcd = models.CharField(max_length=500,default='0')
    # A_5_descr = models.CharField(max_length=500,default='_')
    # A_5_brand = models.CharField(max_length=500,default='_')
    # A_5_qty = models.IntegerField()
    # A_6_qty_rcd = models.CharField(max_length=500,default='0')
    # A_6_descr = models.CharField(max_length=500,default='_')
    # A_6_brand = models.CharField(max_length=500,default='_')
    # A_6_qty = models.IntegerField()
    # A_7_qty_rcd = models.CharField(max_length=500,default='0')
    # A_7_descr = models.CharField(max_length=500,default='_')
    # A_7_brand = models.CharField(max_length=500,default='_')
    # A_7_qty = models.IntegerField()
    # A_8_qty_rcd = models.CharField(max_length=500,default='0')
    # A_8_descr = models.CharField(max_length=500,default='_')
    # A_8_brand = models.CharField(max_length=500,default='_')
    # A_8_qty = models.IntegerField()
    # A_9_qty_rcd = models.CharField(max_length=500,default='0')
    # A_9_descr = models.CharField(max_length=500,default='_')
    # A_9_brand = models.CharField(max_length=500,default='_')
    # A_9_qty = models.IntegerField()
    # A_9B_qty_rcd = models.CharField(max_length=500,default='0')
    # A_9B_descr = models.CharField(max_length=500,default='_')
    # A_9B_brand = models.CharField(max_length=500,default='_')
    # A_9B_qty = models.IntegerField()
    # A_10A_qty_rcd = models.CharField(max_length=500,default='0')
    # A_10A_descr = models.CharField(max_length=500,default='_')
    # A_10A_brand = models.CharField(max_length=500,default='_')

class CardiacRequested(models.Model):
    docnumber = models.CharField(max_length=100,primary_key=True,default="_")
    A_1_name = models.CharField(max_length=500,default='ACT Tubes')
    A_1_descr = models.CharField(max_length=500,default='_')
    A_1_brand = models.CharField(max_length=500,default='_')
    A_1_qty = models.CharField(max_length=100,default='0',blank=True)
    A_2A_name = models.CharField(max_length=500,default='Arterial line cannula (Adult)')
    A_2A_descr = models.CharField(max_length=500,default='_')
    A_2A_brand = models.CharField(max_length=500,default='_')
    A_2A_qty = models.CharField(max_length=100,default='0',blank=True)
    A_2B_name = models.CharField(max_length=500,default='Arterial line cannula (Pediatric)')
    A_2B_descr = models.CharField(max_length=500,default='_')
    A_2B_brand = models.CharField(max_length=500,default='_')
    A_2B_qty = models.CharField(max_length=100,default='0',blank=True)
    A_3A_name = models.CharField(max_length=500,default='Blood glucose strip')
    A_3A_descr = models.CharField(max_length=500,default='_')
    A_3A_brand = models.CharField(max_length=500,default='_')
    A_3A_qty = models.CharField(max_length=100,default='0',blank=True)
    A_3B_name = models.CharField(max_length=500,default='Blood transfusion Set')
    A_3B_descr = models.CharField(max_length=500,default='_')
    A_3B_brand = models.CharField(max_length=500,default='_')
    A_3B_qty = models.CharField(max_length=100,default='0',blank=True)
    # A_4_name = models.CharField(max_length=500,default='BIS Sensor')
    # A_4_descr = models.CharField(max_length=500,default='_')
    # A_4_brand = models.CharField(max_length=500,default='_')
    # A_4_qty = models.IntegerField()
    # A_5_name = models.CharField(max_length=500,default='Bronchial blocker')
    # A_5_descr = models.CharField(max_length=500,default='_')
    # A_5_brand = models.CharField(max_length=500,default='_')
    # A_5_qty = models.IntegerField()
    # A_6_name = models.CharField(max_length=500,default='_')
    # A_6_descr = models.CharField(max_length=500,default='_')
    # A_6_brand = models.CharField(max_length=500,default='_')
    # A_6_qty = models.IntegerField()
    # A_7_name = models.CharField(max_length=500,default='_')
    # A_7_descr = models.CharField(max_length=500,default='_')
    # A_7_brand = models.CharField(max_length=500,default='_')
    # A_7_qty = models.IntegerField()
    # A_8_name = models.CharField(max_length=500,default='_')
    # A_8_descr = models.CharField(max_length=500,default='_')
    # A_8_brand = models.CharField(max_length=500,default='_')
    # A_8_qty = models.IntegerField()
    # A_9_name = models.CharField(max_length=500,default='_')
    # A_9_descr = models.CharField(max_length=500,default='_')
    # A_9_brand = models.CharField(max_length=500,default='_')
    # A_9_qty = models.IntegerField()
    # A_9B_name = models.CharField(max_length=500,default='_')
    # A_9B_descr = models.CharField(max_length=500,default='_')
    # A_9B_brand = models.CharField(max_length=500,default='_')
    # A_9B_qty = models.IntegerField()
    # A_10A_name = models.CharField(max_length=500,default='_')
    # A_10A_descr = models.CharField(max_length=500,default='_')
    # A_10A_brand = models.CharField(max_length=500,default='_')
    # A_10A_qty = models.IntegerField()
    # A_10B_name = models.CharField(max_length=500,default='_')
    # A_10B_descr = models.CharField(max_length=500,default='_')
    # A_10B_brand = models.CharField(max_length=500,default='_')
    # A_10B_qty = models.IntegerField()
    # A_11A_name = models.CharField(max_length=500,default='_')
    # A_11A_descr = models.CharField(max_length=500,default='_')
    # A_11A_brand = models.CharField(max_length=500,default='_')
    # A_11A_qty = models.IntegerField()
    # A_11B_name = models.CharField(max_length=500,default='_')
    # A_11B_descr = models.CharField(max_length=500,default='_')
    # A_11B_brand = models.CharField(max_length=500,default='_')
    # A_11B_qty = models.IntegerField()
    # A_12_name = models.CharField(max_length=500,default='_')
    # A_12_descr = models.CharField(max_length=500,default='_')
    # A_12_brand = models.CharField(max_length=500,default='_')
    # A_12_qty = models.IntegerField()
    # A_13_name = models.CharField(max_length=500,default='_')
    # A_13_descr = models.CharField(max_length=500,default='_')
    # A_13_brand = models.CharField(max_length=500,default='_')
    # A_13_qty = models.IntegerField()
    # A_14A_name = models.CharField(max_length=500,default='_')
    # A_14A_descr = models.CharField(max_length=500,default='_')
    # A_14A_brand = models.CharField(max_length=500,default='_')
    # A_14A_qty = models.IntegerField()
    # A_14B_name = models.CharField(max_length=500,default='_')
    # A_14B_descr = models.CharField(max_length=500,default='_')
    # A_14B_brand = models.CharField(max_length=500,default='_')
    # A_14B_qty = models.IntegerField()
    # A_15_name = models.CharField(max_length=500,default='_')
    # A_15_descr = models.CharField(max_length=500,default='_')
    # A_15_brand = models.CharField(max_length=500,default='_')
    # A_15_qty = models.IntegerField()
    # A_16A_name = models.CharField(max_length=500,default='_')
    # A_16A_descr = models.CharField(max_length=500,default='_')
    # A_16A_brand = models.CharField(max_length=500,default='_')
    # A_16A_qty = models.IntegerField()
    # A_16B_name = models.CharField(max_length=500,default='_')
    # A_16B_descr = models.CharField(max_length=500,default='_')
    # A_16B_brand = models.CharField(max_length=500,default='_')
    # A_16B_qty = models.IntegerField()
    # A_16C_name = models.CharField(max_length=500,default='_')
    # A_16C_descr = models.CharField(max_length=500,default='_')
    # A_16C_brand = models.CharField(max_length=500,default='_')
    # A_16C_qty = models.IntegerField()
    # A_17_name = models.CharField(max_length=500,default='_')
    # A_17_descr = models.CharField(max_length=500,default='_')
    # A_17_brand = models.CharField(max_length=500,default='_')
    # A_17_qty = models.IntegerField()
    # A_18_name = models.CharField(max_length=500,default='_')
    # A_18_descr = models.CharField(max_length=500,default='_')
    # A_18_brand = models.CharField(max_length=500,default='_')
    # A_18_qty = models.IntegerField()
    # A_19_name = models.CharField(max_length=500,default='_')
    # A_19_descr = models.CharField(max_length=500,default='_')
    # A_19_brand = models.CharField(max_length=500,default='_')
    # A_19_qty = models.IntegerField()
    # A_20_name = models.CharField(max_length=500,default='_')
    # A_20_descr = models.CharField(max_length=500,default='_')
    # A_20_brand = models.CharField(max_length=500,default='_')
    # A_20_qty = models.IntegerField()
    # A_21_name = models.CharField(max_length=500,default='_')
    # A_21_descr = models.CharField(max_length=500,default='_')
    # A_21_brand = models.CharField(max_length=500,default='_')
    # A_21_qty = models.IntegerField()
    # A_22_name = models.CharField(max_length=500,default='_')
    # A_22_descr = models.CharField(max_length=500,default='_')
    # A_22_brand = models.CharField(max_length=500,default='_')
    # A_22_qty = models.IntegerField()
    # A_23_name = models.CharField(max_length=500,default='_')
    # A_23_descr = models.CharField(max_length=500,default='_')
    # A_23_brand = models.CharField(max_length=500,default='_')
    # A_23_qty = models.IntegerField()
    # A_24_name = models.CharField(max_length=500,default='_')
    # A_24_descr = models.CharField(max_length=500,default='_')
    # A_24_brand = models.CharField(max_length=500,default='_')
    # A_24_qty = models.IntegerField()
    # A_25_name = models.CharField(max_length=500,default='_')
    # A_25_descr = models.CharField(max_length=500,default='_')
    # A_25_brand = models.CharField(max_length=500,default='_')
    # A_25_qty = models.IntegerField()
    # A_26_name = models.CharField(max_length=500,default='_')
    # A_26_descr = models.CharField(max_length=500,default='_')
    # A_26_brand = models.CharField(max_length=500,default='_')
    # A_26_qty = models.IntegerField()
    # A_27_name = models.CharField(max_length=500,default='_')
    # A_27_descr = models.CharField(max_length=500,default='_')
    # A_27_brand = models.CharField(max_length=500,default='_')
    # A_27_qty = models.IntegerField()
    # A_28_name = models.CharField(max_length=500,default='_')
    # A_28_descr = models.CharField(max_length=500,default='_')
    # A_28_brand = models.CharField(max_length=500,default='_')
    # A_28_qty = models.IntegerField()
    # A_29_name = models.CharField(max_length=500,default='_')
    # A_29_descr = models.CharField(max_length=500,default='_')
    # A_29_brand = models.CharField(max_length=500,default='_')
    # A_29_qty = models.IntegerField()
    # A_30_name = models.CharField(max_length=500,default='_')
    # A_30_descr = models.CharField(max_length=500,default='_')
    # A_30_brand = models.CharField(max_length=500,default='_')
    # A_30_qty = models.IntegerField()
    # A_31_name = models.CharField(max_length=500,default='_')
    # A_31_descr = models.CharField(max_length=500,default='_')
    # A_31_brand = models.CharField(max_length=500,default='_')
    # A_31_qty = models.IntegerField()
    # A_32_name = models.CharField(max_length=500,default='_')
    # A_32_descr = models.CharField(max_length=500,default='_')
    # A_32_brand = models.CharField(max_length=500,default='_')
    # A_32_qty = models.IntegerField()
    # A_33_name = models.CharField(max_length=500,default='_')
    # A_33_descr = models.CharField(max_length=500,default='_')
    # A_33_brand = models.CharField(max_length=500,default='_')
    # A_33_qty = models.IntegerField()
    # A_35_name = models.CharField(max_length=500,default='_')
    # A_35_descr = models.CharField(max_length=500,default='_')
    # A_35_brand = models.CharField(max_length=500,default='_')
    # A_35_qty = models.IntegerField()
    # A_36_name = models.CharField(max_length=500,default='_')
    # A_36_descr = models.CharField(max_length=500,default='_')
    # A_36_brand = models.CharField(max_length=500,default='_')
    # A_36_qty = models.IntegerField()
    # A_37A_name = models.CharField(max_length=500,default='_')
    # A_37A_descr = models.CharField(max_length=500,default='_')
    # A_37A_brand = models.CharField(max_length=500,default='_')
    # A_37A_qty = models.IntegerField()
    # A_37B_name = models.CharField(max_length=500,default='_')
    # A_37B_descr = models.CharField(max_length=500,default='_')
    # A_37B_brand = models.CharField(max_length=500,default='_')
    # A_37B_qty = models.IntegerField()
    # A_38_name = models.CharField(max_length=500,default='_')
    # A_38_descr = models.CharField(max_length=500,default='_')
    # A_38_brand = models.CharField(max_length=500,default='_')
    # A_38_qty = models.IntegerField()
    # A_39_name = models.CharField(max_length=500,default='_')
    # A_39_descr = models.CharField(max_length=500,default='_')
    # A_39_brand = models.CharField(max_length=500,default='_')
    # A_39_qty = models.IntegerField()
    # A_40_name = models.CharField(max_length=500,default='_')
    # A_40_descr = models.CharField(max_length=500,default='_')
    # A_40_brand = models.CharField(max_length=500,default='_')
    # A_40_qty = models.IntegerField()
    # A_41_name = models.CharField(max_length=500,default='_')
    # A_41_descr = models.CharField(max_length=500,default='_')
    # A_41_brand = models.CharField(max_length=500,default='_')
    # A_41_qty = models.IntegerField()
    # A_42_name = models.CharField(max_length=500,default='_')
    # A_42_descr = models.CharField(max_length=500,default='_')
    # A_42_brand = models.CharField(max_length=500,default='_')
    # A_42_qty = models.IntegerField()
    # A_43_name = models.CharField(max_length=500,default='_')
    # A_43_descr = models.CharField(max_length=500,default='_')
    # A_43_brand = models.CharField(max_length=500,default='_')
    # A_43_qty = models.IntegerField()
    # A_44_name = models.CharField(max_length=500,default='_')
    # A_44_descr = models.CharField(max_length=500,default='_')
    # A_44_brand = models.CharField(max_length=500,default='_')
    # A_44_qty = models.IntegerField()
    # A_45_name = models.CharField(max_length=500,default='_')
    # A_45_descr = models.CharField(max_length=500,default='_')
    # A_45_brand = models.CharField(max_length=500,default='_')
    # A_45_qty = models.IntegerField()
    ########################################################
    B_1_name = models.CharField(max_length=500,default='_')
    B_1_descr = models.CharField(max_length=500,default='_')
    B_1_brand = models.CharField(max_length=500,default='_')
    B_1_qty = models.IntegerField()
    B_2A_name = models.CharField(max_length=500,default='_')
    B_2A_descr = models.CharField(max_length=500,default='_')
    B_2A_brand = models.CharField(max_length=500,default='_')
    B_2A_qty = models.IntegerField()
    B_2B_name = models.CharField(max_length=500,default='_')
    B_2B_descr = models.CharField(max_length=500,default='_')
    B_2B_brand = models.CharField(max_length=500,default='_')
    B_2B_qty = models.IntegerField()
    B_3A_name = models.CharField(max_length=500,default='_')
    B_3A_descr = models.CharField(max_length=500,default='_')
    B_3A_brand = models.CharField(max_length=500,default='_')
    B_3A_qty = models.IntegerField()
    B_3B_name = models.CharField(max_length=500,default='_')
    B_3B_descr = models.CharField(max_length=500,default='_')
    B_3B_brand = models.CharField(max_length=500,default='_')
    B_3B_qty = models.IntegerField()
    B_3C_name = models.CharField(max_length=500,default='_')
    B_3C_descr = models.CharField(max_length=500,default='_')
    B_3C_brand = models.CharField(max_length=500,default='_')
    B_3C_qty = models.IntegerField()
    B_3D_name = models.CharField(max_length=500,default='_')
    B_3D_descr = models.CharField(max_length=500,default='_')
    B_3D_brand = models.CharField(max_length=500,default='_')
    B_3D_qty = models.IntegerField()
    # B_4_name = models.CharField(max_length=500,default='_')
    # B_4_descr = models.CharField(max_length=500,default='_')
    # B_4_brand = models.CharField(max_length=500,default='_')
    # B_4_qty = models.IntegerField()
    # B_5A_name = models.CharField(max_length=500,default='_')
    # B_5A_descr = models.CharField(max_length=500,default='_')
    # B_5A_brand = models.CharField(max_length=500,default='_')
    # B_5A_qty = models.IntegerField()
    # B_5B_name = models.CharField(max_length=500,default='_')
    # B_5B_descr = models.CharField(max_length=500,default='_')
    # B_5B_brand = models.CharField(max_length=500,default='_')
    # B_5B_qty = models.IntegerField()
    # B_5C_name = models.CharField(max_length=500,default='_')
    # B_5C_descr = models.CharField(max_length=500,default='_')
    # B_5C_brand = models.CharField(max_length=500,default='_')
    # B_5C_qty = models.IntegerField()
    # B_5D_name = models.CharField(max_length=500,default='_')
    # B_5D_descr = models.CharField(max_length=500,default='_')
    # B_5D_brand = models.CharField(max_length=500,default='_')
    # B_5D_qty = models.IntegerField()
    # B_5E_name = models.CharField(max_length=500,default='_')
    # B_5E_descr = models.CharField(max_length=500,default='_')
    # B_5E_brand = models.CharField(max_length=500,default='_')
    # B_5E_qty = models.IntegerField()
    # B_6_name = models.CharField(max_length=500,default='_')
    # B_6_descr = models.CharField(max_length=500,default='_')
    # B_6_brand = models.CharField(max_length=500,default='_')
    # B_6_qty = models.IntegerField()
    # B_7A_name = models.CharField(max_length=500,default='_')
    # B_7A_descr = models.CharField(max_length=500,default='_')
    # B_7A_brand = models.CharField(max_length=500,default='_')
    # B_7A_qty = models.IntegerField()
    # B_7B_name = models.CharField(max_length=500,default='_')
    # B_7B_descr = models.CharField(max_length=500,default='_')
    # B_7B_brand = models.CharField(max_length=500,default='_')
    # B_7B_qty = models.IntegerField()
    # B_7C_name = models.CharField(max_length=500,default='_')
    # B_7C_descr = models.CharField(max_length=500,default='_')
    # B_7C_brand = models.CharField(max_length=500,default='_')
    # B_7C_qty = models.IntegerField()
    # B_8_name = models.CharField(max_length=500,default='_')
    # B_8_descr = models.CharField(max_length=500,default='_')
    # B_8_brand = models.CharField(max_length=500,default='_')
    # B_8_qty = models.IntegerField()
    # B_9A_name = models.CharField(max_length=500,default='_')
    # B_9A_descr = models.CharField(max_length=500,default='_')
    # B_9A_brand = models.CharField(max_length=500,default='_')
    # B_9A_qty = models.IntegerField()
    # B_9B_name = models.CharField(max_length=500,default='_')
    # B_9B_descr = models.CharField(max_length=500,default='_')
    # B_9B_brand = models.CharField(max_length=500,default='_')
    # B_9B_qty = models.IntegerField()
    # B_9C_name = models.CharField(max_length=500,default='_')
    # B_9C_descr = models.CharField(max_length=500,default='_')
    # B_9C_brand = models.CharField(max_length=500,default='_')
    # B_9C_qty = models.IntegerField()
    # B_10A_name = models.CharField(max_length=500,default='_')
    # B_10A_descr = models.CharField(max_length=500,default='_')
    # B_10A_brand = models.CharField(max_length=500,default='_')
    # B_10A_qty = models.IntegerField()
    # B_10B_name = models.CharField(max_length=500,default='_')
    # B_10B_descr = models.CharField(max_length=500,default='_')
    # B_10B_brand = models.CharField(max_length=500,default='_')
    # B_10B_qty = models.IntegerField()
    # B_11A_name = models.CharField(max_length=500,default='_')
    # B_11A_descr = models.CharField(max_length=500,default='_')
    # B_11A_brand = models.CharField(max_length=500,default='_')
    # B_11A_qty = models.IntegerField()
    # B_11B_name = models.CharField(max_length=500,default='_')
    # B_11B_descr = models.CharField(max_length=500,default='_')
    # B_11B_brand = models.CharField(max_length=500,default='_')
    # B_11B_qty = models.IntegerField()
    # B_11C_name = models.CharField(max_length=500,default='_')
    # B_11C_descr = models.CharField(max_length=500,default='_')
    # B_11C_brand = models.CharField(max_length=500,default='_')
    # B_11C_qty = models.IntegerField()
    # B_12_name = models.CharField(max_length=500,default='_')
    # B_12_descr = models.CharField(max_length=500,default='_')
    # B_12_brand = models.CharField(max_length=500,default='_')
    # B_12_qty = models.IntegerField()
    # B_13A_name = models.CharField(max_length=500,default='_')
    # B_13A_descr = models.CharField(max_length=500,default='_')
    # B_13A_brand = models.CharField(max_length=500,default='_')
    # B_13A_qty = models.IntegerField()
    # B_13B_name = models.CharField(max_length=500,default='_')
    # B_13B_descr = models.CharField(max_length=500,default='_')
    # B_13B_brand = models.CharField(max_length=500,default='_')
    # B_13B_qty = models.IntegerField()
    # B_13C_name = models.CharField(max_length=500,default='_')
    # B_13C_descr = models.CharField(max_length=500,default='_')
    # B_13C_brand = models.CharField(max_length=500,default='_')
    # B_13C_qty = models.IntegerField()
    # B_13D_name = models.CharField(max_length=500,default='_')
    # B_13D_descr = models.CharField(max_length=500,default='_')
    # B_13D_brand = models.CharField(max_length=500,default='_')
    # B_13D_qty = models.IntegerField()
    # B_14_name = models.CharField(max_length=500,default='_')
    # B_14_descr = models.CharField(max_length=500,default='_')
    # B_14_brand = models.CharField(max_length=500,default='_')
    # B_14_qty = models.IntegerField()
    # B_15_name = models.CharField(max_length=500,default='_')
    # B_15_descr = models.CharField(max_length=500,default='_')
    # B_15_brand = models.CharField(max_length=500,default='_')
    # B_15_qty = models.IntegerField()
    # B_16_name = models.CharField(max_length=500,default='_')
    # B_16_descr = models.CharField(max_length=500,default='_')
    # B_16_brand = models.CharField(max_length=500,default='_')
    # B_16_qty = models.IntegerField()
    # B_17A_name = models.CharField(max_length=500,default='_')
    # B_17A_descr = models.CharField(max_length=500,default='_')
    # B_17A_brand = models.CharField(max_length=500,default='_')
    # B_17A_qty = models.IntegerField()
    # B_127B_name = models.CharField(max_length=500,default='_')
    # B_127B_descr = models.CharField(max_length=500,default='_')
    # B_127B_brand = models.CharField(max_length=500,default='_')
    # B_127B_qty = models.IntegerField()
    # B_17C_name = models.CharField(max_length=500,default='_')
    # B_17C_descr = models.CharField(max_length=500,default='_')
    # B_17C_brand = models.CharField(max_length=500,default='_')
    # B_17C_qty = models.IntegerField()
    # B_17D_name = models.CharField(max_length=500,default='_')
    # B_17D_descr = models.CharField(max_length=500,default='_')
    # B_17D_brand = models.CharField(max_length=500,default='_')
    # B_17D_qty = models.IntegerField()
    # B_18A_name = models.CharField(max_length=500,default='_')
    # B_18A_descr = models.CharField(max_length=500,default='_')
    # B_18A_brand = models.CharField(max_length=500,default='_')
    # B_18A_qty = models.IntegerField()
    # B_18B_name = models.CharField(max_length=500,default='_')
    # B_18B_descr = models.CharField(max_length=500,default='_')
    # B_18B_brand = models.CharField(max_length=500,default='_')
    # B_18B_qty = models.IntegerField()
    # B_19A_name = models.CharField(max_length=500,default='_')
    # B_19A_descr = models.CharField(max_length=500,default='_')
    # B_19A_brand = models.CharField(max_length=500,default='_')
    # B_19A_qty = models.IntegerField()
    # B_19B_name = models.CharField(max_length=500,default='_')
    # B_19B_descr = models.CharField(max_length=500,default='_')
    # B_19B_brand = models.CharField(max_length=500,default='_')
    # B_19B_qty = models.IntegerField()
    # B_19C_name = models.CharField(max_length=500,default='_')
    # B_19C_descr = models.CharField(max_length=500,default='_')
    # B_19C_brand = models.CharField(max_length=500,default='_')
    # B_19C_qty = models.IntegerField()
    # B_20A_name = models.CharField(max_length=500,default='_')
    # B_20A_descr = models.CharField(max_length=500,default='_')
    # B_20A_brand = models.CharField(max_length=500,default='_')
    # B_20A_qty = models.IntegerField()
    # B_20B_name = models.CharField(max_length=500,default='_')
    # B_20B_descr = models.CharField(max_length=500,default='_')
    # B_20B_brand = models.CharField(max_length=500,default='_')
    # B_20B_qty = models.IntegerField()
    # B_20C_name = models.CharField(max_length=500,default='_')
    # B_20C_descr = models.CharField(max_length=500,default='_')
    # B_20C_brand = models.CharField(max_length=500,default='_')
    # B_20C_qty = models.IntegerField()
    # B_21_name = models.CharField(max_length=500,default='_')
    # B_21_descr = models.CharField(max_length=500,default='_')
    # B_21_brand = models.CharField(max_length=500,default='_')
    # B_21_qty = models.IntegerField()
    # B_22_name = models.CharField(max_length=500,default='_')
    # B_22_descr = models.CharField(max_length=500,default='_')
    # B_22_brand = models.CharField(max_length=500,default='_')
    # B_22_qty = models.IntegerField()

    # #####################################################
    # C_1_name = models.CharField(max_length=500,default='_')
    # C_1_descr = models.CharField(max_length=500,default='_')
    # C_1_brand = models.CharField(max_length=500,default='_')
    # C_1_qty = models.IntegerField()
    # C_2A_name = models.CharField(max_length=500,default='_')
    # C_2A_descr = models.CharField(max_length=500,default='_')
    # C_2A_brand = models.CharField(max_length=500,default='_')
    # C_2A_qty = models.IntegerField()
    # C_2B_name = models.CharField(max_length=500,default='_')
    # C_2B_descr = models.CharField(max_length=500,default='_')
    # C_2B_brand = models.CharField(max_length=500,default='_')
    # C_2B_qty = models.IntegerField()
    # C_2C_name = models.CharField(max_length=500,default='_')
    # C_2C_descr = models.CharField(max_length=500,default='_')
    # C_2C_brand = models.CharField(max_length=500,default='_')
    # C_2C_qty = models.IntegerField()
    # C_3_name = models.CharField(max_length=500,default='_')
    # C_3_descr = models.CharField(max_length=500,default='_')
    # C_3_brand = models.CharField(max_length=500,default='_')
    # C_3_qty = models.IntegerField()
    # C_4_name = models.CharField(max_length=500,default='_')
    # C_4_descr = models.CharField(max_length=500,default='_')
    # C_4_brand = models.CharField(max_length=500,default='_')
    # C_4_qty = models.IntegerField()
    # C_5_name = models.CharField(max_length=500,default='_')
    # C_5_descr = models.CharField(max_length=500,default='_')
    # C_5_brand = models.CharField(max_length=500,default='_')
    # C_5_qty = models.IntegerField()
    # C_6_name = models.CharField(max_length=500,default='_')
    # C_6_descr = models.CharField(max_length=500,default='_')
    # C_6_brand = models.CharField(max_length=500,default='_')
    # C_6_qty = models.IntegerField()
    # C_7_name = models.CharField(max_length=500,default='_')
    # C_7_descr = models.CharField(max_length=500,default='_')
    # C_7_brand = models.CharField(max_length=500,default='_')
    # C_7_qty = models.IntegerField()
    # C_8_name = models.CharField(max_length=500,default='_')
    # C_8_descr = models.CharField(max_length=500,default='_')
    # C_8_brand = models.CharField(max_length=500,default='_')
    # C_8_qty = models.IntegerField()
    # C_9_name = models.CharField(max_length=500,default='_')
    # C_9_descr = models.CharField(max_length=500,default='_')
    # C_9_brand = models.CharField(max_length=500,default='_')
    # C_9_qty = models.IntegerField()
    # C_10_name = models.CharField(max_length=500,default='_')
    # C_10_descr = models.CharField(max_length=500,default='_')
    # C_10_brand = models.CharField(max_length=500,default='_')
    # C_10_qty = models.IntegerField()
    # C_11_name = models.CharField(max_length=500,default='_')
    # C_11_descr = models.CharField(max_length=500,default='_')
    # C_11_brand = models.CharField(max_length=500,default='_')
    # C_11_qty = models.IntegerField()
    # C_12_name = models.CharField(max_length=500,default='_')
    # C_12_descr = models.CharField(max_length=500,default='_')
    # C_12_brand = models.CharField(max_length=500,default='_')
    # C_12_qty = models.IntegerField()
    # C_13_name = models.CharField(max_length=500,default='_')
    # C_13_descr = models.CharField(max_length=500,default='_')
    # C_13_brand = models.CharField(max_length=500,default='_')
    # C_13_qty = models.IntegerField()
    # C_14_name = models.CharField(max_length=500,default='_')
    # C_14_descr = models.CharField(max_length=500,default='_')
    # C_14_brand = models.CharField(max_length=500,default='_')
    # C_14_qty = models.IntegerField()
    # C_15A_name = models.CharField(max_length=500,default='_')
    # C_15A_descr = models.CharField(max_length=500,default='_')
    # C_15A_brand = models.CharField(max_length=500,default='_')
    # C_15A_qty = models.IntegerField()
    # C_15B_name = models.CharField(max_length=500,default='_')
    # C_15B_descr = models.CharField(max_length=500,default='_')
    # C_15B_brand = models.CharField(max_length=500,default='_')
    # C_15B_qty = models.IntegerField()
    # C_16_name = models.CharField(max_length=500,default='_')
    # C_16_descr = models.CharField(max_length=500,default='_')
    # C_16_brand = models.CharField(max_length=500,default='_')
    # C_16_qty = models.IntegerField()
    # C_17A_name = models.CharField(max_length=500,default='_')
    # C_17A_descr = models.CharField(max_length=500,default='_')
    # C_17A_brand = models.CharField(max_length=500,default='_')
    # C_17A_qty = models.IntegerField()
    # C_17B_name = models.CharField(max_length=500,default='_')
    # C_17B_descr = models.CharField(max_length=500,default='_')
    # C_17B_brand = models.CharField(max_length=500,default='_')
    # C_17B_qty = models.IntegerField()
    # C_17C_name = models.CharField(max_length=500,default='_')
    # C_17C_descr = models.CharField(max_length=500,default='_')
    # C_17C_brand = models.CharField(max_length=500,default='_')
    # C_17C_qty = models.IntegerField()
    # C_18_name = models.CharField(max_length=500,default='_')
    # C_18_descr = models.CharField(max_length=500,default='_')
    # C_18_brand = models.CharField(max_length=500,default='_')
    # C_18_qty = models.IntegerField()
    # C_19_name = models.CharField(max_length=500,default='_')
    # C_19_descr = models.CharField(max_length=500,default='_')
    # C_19_brand = models.CharField(max_length=500,default='_')
    # C_19_qty = models.IntegerField()
    # C_20_name = models.CharField(max_length=500,default='_')
    # C_20_descr = models.CharField(max_length=500,default='_')
    # C_20_brand = models.CharField(max_length=500,default='_')
    # C_20_qty = models.IntegerField()
    # C_21_name = models.CharField(max_length=500,default='_')
    # C_21_descr = models.CharField(max_length=500,default='_')
    # C_21_brand = models.CharField(max_length=500,default='_')
    # C_21_qty = models.IntegerField()
    # C_22_name = models.CharField(max_length=500,default='_')
    # C_22_descr = models.CharField(max_length=500,default='_')
    # C_22_brand = models.CharField(max_length=500,default='_')
    # C_22_qty = models.IntegerField()
    # C_23_name = models.CharField(max_length=500,default='_')
    # C_23_descr = models.CharField(max_length=500,default='_')
    # C_23_brand = models.CharField(max_length=500,default='_')
    # C_23_qty = models.IntegerField()
    # C_24_name = models.CharField(max_length=500,default='_')
    # C_24_descr = models.CharField(max_length=500,default='_')
    # C_24_brand = models.CharField(max_length=500,default='_')
    # C_24_qty = models.IntegerField()
    # C_25_name = models.CharField(max_length=500,default='_')
    # C_25_descr = models.CharField(max_length=500,default='_')
    # C_25_brand = models.CharField(max_length=500,default='_')
    # C_25_qty = models.IntegerField()
    # C_26_name = models.CharField(max_length=500,default='_')
    # C_26_descr = models.CharField(max_length=500,default='_')
    # C_26_brand = models.CharField(max_length=500,default='_')
    # C_26_qty = models.IntegerField()
    # C_27_name = models.CharField(max_length=500,default='_')
    # C_27_descr = models.CharField(max_length=500,default='_')
    # C_27_brand = models.CharField(max_length=500,default='_')
    # C_27_qty = models.IntegerField()
    # C_28_name = models.CharField(max_length=500,default='_')
    # C_28_descr = models.CharField(max_length=500,default='_')
    # C_28_brand = models.CharField(max_length=500,default='_')
    # C_28_qty = models.IntegerField()
    # C_29_name = models.CharField(max_length=500,default='_')
    # C_29_descr = models.CharField(max_length=500,default='_')
    # C_29_brand = models.CharField(max_length=500,default='_')
    # C_29_qty = models.IntegerField()
    # C_30_name = models.CharField(max_length=500,default='_')
    # C_30_descr = models.CharField(max_length=500,default='_')
    # C_30_brand = models.CharField(max_length=500,default='_')
    # C_30_qty = models.IntegerField()
    # C_31_name = models.CharField(max_length=500,default='_')
    # C_31_descr = models.CharField(max_length=500,default='_')
    # C_31_brand = models.CharField(max_length=500,default='_')
    # C_31_qty = models.IntegerField()
    # C_32A_name = models.CharField(max_length=500,default='_')
    # C_32A_descr = models.CharField(max_length=500,default='_')
    # C_32A_brand = models.CharField(max_length=500,default='_')
    # C_32A_qty = models.IntegerField()
    # C_32B_name = models.CharField(max_length=500,default='_')
    # C_32B_descr = models.CharField(max_length=500,default='_')
    # C_32B_brand = models.CharField(max_length=500,default='_')
    # C_32B_qty = models.IntegerField()
    # C_33_name = models.CharField(max_length=500,default='_')
    # C_33_descr = models.CharField(max_length=500,default='_')
    # C_33_brand = models.CharField(max_length=500,default='_')
    # C_33_qty = models.IntegerField()
    # C_34_name = models.CharField(max_length=500,default='_')
    # C_34_descr = models.CharField(max_length=500,default='_')
    # C_34_brand = models.CharField(max_length=500,default='_')
    # C_34_qty = models.IntegerField()
    # C_35_name = models.CharField(max_length=500,default='_')
    # C_35_descr = models.CharField(max_length=500,default='_')
    # C_35_brand = models.CharField(max_length=500,default='_')
    # C_35_qty = models.IntegerField()
    # C_36_name = models.CharField(max_length=500,default='_')
    # C_36_descr = models.CharField(max_length=500,default='_')
    # C_36_brand = models.CharField(max_length=500,default='_')
    # C_36_qty = models.IntegerField()
    # C_37_name = models.CharField(max_length=500,default='_')
    # C_37_descr = models.CharField(max_length=500,default='_')
    # C_37_brand = models.CharField(max_length=500,default='_')
    # C_37_qty = models.IntegerField()
    # C_38_name = models.CharField(max_length=500,default='_')
    # C_38_descr = models.CharField(max_length=500,default='_')
    # C_38_brand = models.CharField(max_length=500,default='_')
    # C_38_qty = models.IntegerField()
    # C_39_name = models.CharField(max_length=500,default='_')
    # C_39_descr = models.CharField(max_length=500,default='_')
    # C_39_brand = models.CharField(max_length=500,default='_')
    # C_39_qty = models.IntegerField()
    # C_40_name = models.CharField(max_length=500,default='_')
    # C_40_descr = models.CharField(max_length=500,default='_')
    # C_40_brand = models.CharField(max_length=500,default='_')
    # C_40_qty = models.IntegerField()
    # C_41_name = models.CharField(max_length=500,default='_')
    # C_41_descr = models.CharField(max_length=500,default='_')
    # C_41_brand = models.CharField(max_length=500,default='_')
    # C_41_qty = models.IntegerField()
    # C_42_name = models.CharField(max_length=500,default='_')
    # C_42_descr = models.CharField(max_length=500,default='_')
    # C_42_brand = models.CharField(max_length=500,default='_')
    # C_42_qty = models.IntegerField()
    # C_43_name = models.CharField(max_length=500,default='_')
    # C_43_descr = models.CharField(max_length=500,default='_')
    # C_43_brand = models.CharField(max_length=500,default='_')
    # C_43_qty = models.IntegerField()
    # ########################################################
    # D_1_name = models.CharField(max_length=500,default='_')
    # D_1_descr = models.CharField(max_length=500,default='_')
    # D_1_brand = models.CharField(max_length=500,default='_')
    # D_1_qty = models.IntegerField()
    # D_2_name = models.CharField(max_length=500,default='_')
    # D_2_descr = models.CharField(max_length=500,default='_')
    # D_2_brand = models.CharField(max_length=500,default='_')
    # D_2_qty = models.IntegerField()
    # D_3_name = models.CharField(max_length=500,default='_')
    # D_3_descr = models.CharField(max_length=500,default='_')
    # D_3_brand = models.CharField(max_length=500,default='_')
    # D_3_qty = models.IntegerField()
    # D_4_name = models.CharField(max_length=500,default='_')
    # D_4_descr = models.CharField(max_length=500,default='_')
    # D_4_brand = models.CharField(max_length=500,default='_')
    # D_4_qty = models.IntegerField()
    # D_5_name = models.CharField(max_length=500,default='_')
    # D_5_descr = models.CharField(max_length=500,default='_')
    # D_5_brand = models.CharField(max_length=500,default='_')
    # D_5_qty = models.IntegerField()
    # D_6_name = models.CharField(max_length=500,default='_')
    # D_6_descr = models.CharField(max_length=500,default='_')
    # D_6_brand = models.CharField(max_length=500,default='_')
    # D_6_qty = models.IntegerField()
    # D_7_name = models.CharField(max_length=500,default='_')
    # D_7_descr = models.CharField(max_length=500,default='_')
    # D_7_brand = models.CharField(max_length=500,default='_')
    # D_7_qty = models.IntegerField()
    # D_8_name = models.CharField(max_length=500,default='_')
    # D_8_descr = models.CharField(max_length=500,default='_')
    # D_8_brand = models.CharField(max_length=500,default='_')
    # D_8_qty = models.IntegerField()
    # D_9_name = models.CharField(max_length=500,default='_')
    # D_9_descr = models.CharField(max_length=500,default='_')
    # D_9_brand = models.CharField(max_length=500,default='_')
    # D_9_qty = models.IntegerField()
    # D_10_name = models.CharField(max_length=500,default='_')
    # D_10_descr = models.CharField(max_length=500,default='_')
    # D_10_brand = models.CharField(max_length=500,default='_')
    # D_10_qty = models.IntegerField()
    # D_11_name = models.CharField(max_length=500,default='_')
    # D_11_descr = models.CharField(max_length=500,default='_')
    # D_11_brand = models.CharField(max_length=500,default='_')
    # D_11_qty = models.IntegerField()
    # D_12_name = models.CharField(max_length=500,default='_')
    # D_12_descr = models.CharField(max_length=500,default='_')
    # D_12_brand = models.CharField(max_length=500,default='_')
    # D_12_qty = models.IntegerField()
    # D_13_name = models.CharField(max_length=500,default='_')
    # D_13_descr = models.CharField(max_length=500,default='_')
    # D_13_brand = models.CharField(max_length=500,default='_')
    # D_13_qty = models.IntegerField()
    # D_14_name = models.CharField(max_length=500,default='_')
    # D_14_descr = models.CharField(max_length=500,default='_')
    # D_14_brand = models.CharField(max_length=500,default='_')
    # D_14_qty = models.IntegerField()
    # D_15_name = models.CharField(max_length=500,default='_')
    # D_15_descr = models.CharField(max_length=500,default='_')
    # D_15_brand = models.CharField(max_length=500,default='_')
    # D_15_qty = models.IntegerField()
    # D_16_name = models.CharField(max_length=500,default='_')
    # D_16_descr = models.CharField(max_length=500,default='_')
    # D_16_brand = models.CharField(max_length=500,default='_')
    # D_16_qty = models.IntegerField()
    # D_17_name = models.CharField(max_length=500,default='_')
    # D_17_descr = models.CharField(max_length=500,default='_')
    # D_17_brand = models.CharField(max_length=500,default='_')
    # D_17_qty = models.IntegerField()
    # D_18_name = models.CharField(max_length=500,default='_')
    # D_18_descr = models.CharField(max_length=500,default='_')
    # D_18_brand = models.CharField(max_length=500,default='_')
    # D_18_qty = models.IntegerField()
    # D_19_name = models.CharField(max_length=500,default='_')
    # D_19_descr = models.CharField(max_length=500,default='_')
    # D_19_brand = models.CharField(max_length=500,default='_')
    # D_19_qty = models.IntegerField()
    # D_20_name = models.CharField(max_length=500,default='_')
    # D_20_descr = models.CharField(max_length=500,default='_')
    # D_20_brand = models.CharField(max_length=500,default='_')
    # D_20_qty = models.IntegerField()
    # D_21_name = models.CharField(max_length=500,default='_')
    # D_21_descr = models.CharField(max_length=500,default='_')
    # D_21_brand = models.CharField(max_length=500,default='_')
    # D_21_qty = models.IntegerField()
    # D_22_name = models.CharField(max_length=500,default='_')
    # D_22_descr = models.CharField(max_length=500,default='_')
    # D_22_brand = models.CharField(max_length=500,default='_')
    # D_22_qty = models.IntegerField()
    # D_23_name = models.CharField(max_length=500,default='_')
    # D_23_descr = models.CharField(max_length=500,default='_')
    # D_23_brand = models.CharField(max_length=500,default='_')
    # D_23_qty = models.IntegerField()
    # D_24A_name = models.CharField(max_length=500,default='_')
    # D_24A_descr = models.CharField(max_length=500,default='_')
    # D_24A_brand = models.CharField(max_length=500,default='_')
    # D_24A_qty = models.IntegerField()
    # D_24B_name = models.CharField(max_length=500,default='_')
    # D_24B_descr = models.CharField(max_length=500,default='_')
    # D_24B_brand = models.CharField(max_length=500,default='_')
    # D_24B_qty = models.IntegerField()
    # D_25_name = models.CharField(max_length=500,default='_')
    # D_25_descr = models.CharField(max_length=500,default='_')
    # D_25_brand = models.CharField(max_length=500,default='_')
    # D_25_qty = models.IntegerField()
    # D_26_name = models.CharField(max_length=500,default='_')
    # D_26_descr = models.CharField(max_length=500,default='_')
    # D_26_brand = models.CharField(max_length=500,default='_')
    # D_26_qty = models.IntegerField()
    # D_27_name = models.CharField(max_length=500,default='_')
    # D_27_descr = models.CharField(max_length=500,default='_')
    # D_27_brand = models.CharField(max_length=500,default='_')
    # D_27_qty = models.IntegerField()
    # D_28_name = models.CharField(max_length=500,default='_')
    # D_28_descr = models.CharField(max_length=500,default='_')
    # D_28_brand = models.CharField(max_length=500,default='_')
    # D_28_qty = models.IntegerField()
    # D_29_name = models.CharField(max_length=500,default='_')
    # D_29_descr = models.CharField(max_length=500,default='_')
    # D_29_brand = models.CharField(max_length=500,default='_')
    # D_29_qty = models.IntegerField()
    # D_30_name = models.CharField(max_length=500,default='_')
    # D_30_descr = models.CharField(max_length=500,default='_')
    # D_30_brand = models.CharField(max_length=500,default='_')
    # D_30_qty = models.IntegerField()
    # D_31_name = models.CharField(max_length=500,default='_')
    # D_31_descr = models.CharField(max_length=500,default='_')
    # D_31_brand = models.CharField(max_length=500,default='_')
    # D_31_qty = models.IntegerField()
    # D_32_name = models.CharField(max_length=500,default='_')
    # D_32_descr = models.CharField(max_length=500,default='_')
    # D_32_brand = models.CharField(max_length=500,default='_')
    # D_32_qty = models.IntegerField()
    # D_33_name = models.CharField(max_length=500,default='_')
    # D_33_descr = models.CharField(max_length=500,default='_')
    # D_33_brand = models.CharField(max_length=500,default='_')
    # D_33_qty = models.IntegerField()
    # D_34_name = models.CharField(max_length=500,default='_')
    # D_34_descr = models.CharField(max_length=500,default='_')
    # D_34_brand = models.CharField(max_length=500,default='_')
    # D_34_qty = models.IntegerField()
    # D_35_name = models.CharField(max_length=500,default='_')
    # D_35_descr = models.CharField(max_length=500,default='_')
    # D_35_brand = models.CharField(max_length=500,default='_')
    # D_35_qty = models.IntegerField()
    # D_36_name = models.CharField(max_length=500,default='_')
    # D_36_descr = models.CharField(max_length=500,default='_')
    # D_36_brand = models.CharField(max_length=500,default='_')
    # D_36_qty = models.IntegerField()
    # D_37_name = models.CharField(max_length=500,default='_')
    # D_37_descr = models.CharField(max_length=500,default='_')
    # D_37_brand = models.CharField(max_length=500,default='_')
    # D_37_qty = models.IntegerField()
    # D_38_name = models.CharField(max_length=500,default='_')
    # D_38_descr = models.CharField(max_length=500,default='_')
    # D_38_brand = models.CharField(max_length=500,default='_')
    # D_38_qty = models.IntegerField()
    # D_39_name = models.CharField(max_length=500,default='_')
    # D_39_descr = models.CharField(max_length=500,default='_')
    # D_39_brand = models.CharField(max_length=500,default='_')
    # D_39_qty = models.IntegerField()
    # D_40_name = models.CharField(max_length=500,default='_')
    # D_40_descr = models.CharField(max_length=500,default='_')
    # D_40_brand = models.CharField(max_length=500,default='_')
    # D_40_qty = models.IntegerField()
    # D_41_name = models.CharField(max_length=500,default='_')
    # D_41_descr = models.CharField(max_length=500,default='_')
    # D_41_brand = models.CharField(max_length=500,default='_')
    # D_41_qty = models.IntegerField()
    # D_42_name = models.CharField(max_length=500,default='_')
    # D_42_descr = models.CharField(max_length=500,default='_')
    # D_42_brand = models.CharField(max_length=500,default='_')
    # D_42_qty = models.IntegerField()
    # D_43_name = models.CharField(max_length=500,default='_')
    # D_43_descr = models.CharField(max_length=500,default='_')
    # D_43_brand = models.CharField(max_length=500,default='_')
    # D_43_qty = models.IntegerField()
    # D_44_name = models.CharField(max_length=500,default='_')
    # D_44_descr = models.CharField(max_length=500,default='_')
    # D_44_brand = models.CharField(max_length=500,default='_')
    # D_44_qty = models.IntegerField()
    # D_45_name = models.CharField(max_length=500,default='_')
    # D_45_descr = models.CharField(max_length=500,default='_')
    # D_45_brand = models.CharField(max_length=500,default='_')
    # D_45_qty = models.IntegerField()
    # D_46_name = models.CharField(max_length=500,default='_')
    # D_46_descr = models.CharField(max_length=500,default='_')
    # D_46_brand = models.CharField(max_length=500,default='_')
    # D_46_qty = models.IntegerField()
    # D_47_name = models.CharField(max_length=500,default='_')
    # D_47_descr = models.CharField(max_length=500,default='_')
    # D_47_brand = models.CharField(max_length=500,default='_')
    # D_47_qty = models.IntegerField()
    # D_48_name = models.CharField(max_length=500,default='_')
    # D_48_descr = models.CharField(max_length=500,default='_')
    # D_48_brand = models.CharField(max_length=500,default='_')
    # D_48_qty = models.IntegerField()
    # D_49_name = models.CharField(max_length=500,default='_')
    # D_49_descr = models.CharField(max_length=500,default='_')
    # D_49_brand = models.CharField(max_length=500,default='_')
    # D_49_qty = models.IntegerField()
    # D_50_name = models.CharField(max_length=500,default='_')
    # D_50_descr = models.CharField(max_length=500,default='_')
    # D_50_brand = models.CharField(max_length=500,default='_')
    # D_50_qty = models.IntegerField()
    # D_51_name = models.CharField(max_length=500,default='_')
    # D_51_descr = models.CharField(max_length=500,default='_')
    # D_51_brand = models.CharField(max_length=500,default='_')
    # D_51_qty = models.IntegerField()
    # D_52_name = models.CharField(max_length=500,default='_')
    # D_52_descr = models.CharField(max_length=500,default='_')
    # D_52_brand = models.CharField(max_length=500,default='_')
    # D_52_qty = models.IntegerField()
    # D_53_name = models.CharField(max_length=500,default='_')
    # D_53_descr = models.CharField(max_length=500,default='_')
    # D_53_brand = models.CharField(max_length=500,default='_')
    # D_53_qty = models.IntegerField()
    # #####################################################
    # E_1_name = models.CharField(max_length=500,default='_')
    # E_1_descr = models.CharField(max_length=500,default='_')
    # E_1_brand = models.CharField(max_length=500,default='_')
    # E_1_qty = models.IntegerField()
    # E_2_name = models.CharField(max_length=500,default='_')
    # E_2_descr = models.CharField(max_length=500,default='_')
    # E_2_brand = models.CharField(max_length=500,default='_')
    # E_2_qty = models.IntegerField()
    # E_3_name = models.CharField(max_length=500,default='_')
    # E_3_descr = models.CharField(max_length=500,default='_')
    # E_3_brand = models.CharField(max_length=500,default='_')
    # E_3_qty = models.IntegerField()
    # E_4_name = models.CharField(max_length=500,default='_')
    # E_4_descr = models.CharField(max_length=500,default='_')
    # E_4_brand = models.CharField(max_length=500,default='_')
    # E_4_qty = models.IntegerField()
    # E_5_name = models.CharField(max_length=500,default='_')
    # E_5_descr = models.CharField(max_length=500,default='_')
    # E_5_brand = models.CharField(max_length=500,default='_')
    # E_5_qty = models.IntegerField()
    # E_6_name = models.CharField(max_length=500,default='_')
    # E_6_descr = models.CharField(max_length=500,default='_')
    # E_6_brand = models.CharField(max_length=500,default='_')
    # E_6_qty = models.IntegerField()
    # E_7_name = models.CharField(max_length=500,default='_')
    # E_7_descr = models.CharField(max_length=500,default='_')
    # E_7_brand = models.CharField(max_length=500,default='_')
    # E_7_qty = models.IntegerField()
    # E_8_name = models.CharField(max_length=500,default='_')
    # E_8_descr = models.CharField(max_length=500,default='_')
    # E_8_brand = models.CharField(max_length=500,default='_')
    # E_8_qty = models.IntegerField()
    # E_9_name = models.CharField(max_length=500,default='_')
    # E_9_descr = models.CharField(max_length=500,default='_')
    # E_9_brand = models.CharField(max_length=500,default='_')
    # E_9_qty = models.IntegerField()
    # E_10_name = models.CharField(max_length=500,default='_')
    # E_10_descr = models.CharField(max_length=500,default='_')
    # E_10_brand = models.CharField(max_length=500,default='_')
    # E_10_qty = models.IntegerField()
    # E_11_name = models.CharField(max_length=500,default='_')
    # E_11_descr = models.CharField(max_length=500,default='_')
    # E_11_brand = models.CharField(max_length=500,default='_')
    # E_11_qty = models.IntegerField()
    # E_12_name = models.CharField(max_length=500,default='_')
    # E_12_descr = models.CharField(max_length=500,default='_')
    # E_12_brand = models.CharField(max_length=500,default='_')
    # E_12_qty = models.IntegerField()
    # E_13_name = models.CharField(max_length=500,default='_')
    # E_13_descr = models.CharField(max_length=500,default='_')
    # E_13_brand = models.CharField(max_length=500,default='_')
    # E_13_qty = models.IntegerField()
    # E_14_name = models.CharField(max_length=500,default='_')
    # E_14_descr = models.CharField(max_length=500,default='_')
    # E_14_brand = models.CharField(max_length=500,default='_')
    # E_14_qty = models.IntegerField()
    # E_15_name = models.CharField(max_length=500,default='_')
    # E_15_descr = models.CharField(max_length=500,default='_')
    # E_15_brand = models.CharField(max_length=500,default='_')
    # E_15_qty = models.IntegerField()
    # E_16_name = models.CharField(max_length=500,default='_')
    # E_16_descr = models.CharField(max_length=500,default='_')
    # E_16_brand = models.CharField(max_length=500,default='_')
    # E_16_qty = models.IntegerField()
    # E_17_name = models.CharField(max_length=500,default='_')
    # E_17_descr = models.CharField(max_length=500,default='_')
    # E_17_brand = models.CharField(max_length=500,default='_')
    # E_17_qty = models.IntegerField()
    # E_18_name = models.CharField(max_length=500,default='_')
    # E_18_descr = models.CharField(max_length=500,default='_')
    # E_18_brand = models.CharField(max_length=500,default='_')
    # E_18_qty = models.IntegerField()
    # E_19_name = models.CharField(max_length=500,default='_')
    # E_19_descr = models.CharField(max_length=500,default='_')
    # E_19_brand = models.CharField(max_length=500,default='_')
    # E_19_qty = models.IntegerField()
    # E_20_name = models.CharField(max_length=500,default='_')
    # E_20_descr = models.CharField(max_length=500,default='_')
    # E_20_brand = models.CharField(max_length=500,default='_')
    # E_20_qty = models.IntegerField()
    # E_21_name = models.CharField(max_length=500,default='_')
    # E_21_descr = models.CharField(max_length=500,default='_')
    # E_21_brand = models.CharField(max_length=500,default='_')
    # E_21_qty = models.IntegerField()
    # E_22_name = models.CharField(max_length=500,default='_')
    # E_22_descr = models.CharField(max_length=500,default='_')
    # E_22_brand = models.CharField(max_length=500,default='_')
    # E_22_qty = models.IntegerField()
    # E_23_name = models.CharField(max_length=500,default='_')
    # E_23_descr = models.CharField(max_length=500,default='_')
    # E_23_brand = models.CharField(max_length=500,default='_')
    # E_23_qty = models.IntegerField()
    # E_24_name = models.CharField(max_length=500,default='_')
    # E_24_descr = models.CharField(max_length=500,default='_')
    # E_24_brand = models.CharField(max_length=500,default='_')
    # E_24_qty = models.IntegerField()
    # E_25_name = models.CharField(max_length=500,default='_')
    # E_25_descr = models.CharField(max_length=500,default='_')
    # E_25_brand = models.CharField(max_length=500,default='_')
    # E_25_qty = models.IntegerField()
    # E_26_name = models.CharField(max_length=500,default='_')
    # E_26_descr = models.CharField(max_length=500,default='_')
    # E_26_brand = models.CharField(max_length=500,default='_')
    # E_26_qty = models.IntegerField()
    # E_27_name = models.CharField(max_length=500,default='_')
    # E_27_descr = models.CharField(max_length=500,default='_')
    # E_27_brand = models.CharField(max_length=500,default='_')
    # E_27_qty = models.IntegerField()
    # E_28_name = models.CharField(max_length=500,default='_')
    # E_28_descr = models.CharField(max_length=500,default='_')
    # E_28_brand = models.CharField(max_length=500,default='_')
    # E_28_qty = models.IntegerField()
    # E_29_name = models.CharField(max_length=500,default='_')
    # E_29_descr = models.CharField(max_length=500,default='_')
    # E_29_brand = models.CharField(max_length=500,default='_')
    # E_29_qty = models.IntegerField()
    # E_30_name = models.CharField(max_length=500,default='_')
    # E_30_descr = models.CharField(max_length=500,default='_')
    # E_30_brand = models.CharField(max_length=500,default='_')
    # E_30_qty = models.IntegerField()
    # E_31_name = models.CharField(max_length=500,default='_')
    # E_31_descr = models.CharField(max_length=500,default='_')
    # E_31_brand = models.CharField(max_length=500,default='_')
    # E_31_qty = models.IntegerField()
    # E_342_name = models.CharField(max_length=500,default='_')
    # E_342_descr = models.CharField(max_length=500,default='_')
    # E_342_brand = models.CharField(max_length=500,default='_')
    # E_342_qty = models.IntegerField()
    # E_33_name = models.CharField(max_length=500,default='_')
    # E_33_descr = models.CharField(max_length=500,default='_')
    # E_33_brand = models.CharField(max_length=500,default='_')
    # E_33_qty = models.IntegerField()
    # E_34_name = models.CharField(max_length=500,default='_')
    # E_34_descr = models.CharField(max_length=500,default='_')
    # E_34_brand = models.CharField(max_length=500,default='_')
    # E_34_qty = models.IntegerField()
    # E_35_name = models.CharField(max_length=500,default='_')
    # E_35_descr = models.CharField(max_length=500,default='_')
    # E_35_brand = models.CharField(max_length=500,default='_')
    # E_35_qty = models.IntegerField()
    # E_36_name = models.CharField(max_length=500,default='_')
    # E_36_descr = models.CharField(max_length=500,default='_')
    # E_36_brand = models.CharField(max_length=500,default='_')
    # E_36_qty = models.IntegerField()
    # E_37_name = models.CharField(max_length=500,default='_')
    # E_37_descr = models.CharField(max_length=500,default='_')
    # E_37_brand = models.CharField(max_length=500,default='_')
    # E_37_qty = models.IntegerField()
    # E_38_name = models.CharField(max_length=500,default='_')
    # E_38_descr = models.CharField(max_length=500,default='_')
    # E_38_brand = models.CharField(max_length=500,default='_')
    # E_38_qty = models.IntegerField()
    # E_39_name = models.CharField(max_length=500,default='_')
    # E_39_descr = models.CharField(max_length=500,default='_')
    # E_39_brand = models.CharField(max_length=500,default='_')
    # E_39_qty = models.IntegerField()
    # E_40_name = models.CharField(max_length=500,default='_')
    # E_40_descr = models.CharField(max_length=500,default='_')
    # E_40_brand = models.CharField(max_length=500,default='_')
    # E_40_qty = models.IntegerField()
    # E_41_name = models.CharField(max_length=500,default='_')
    # E_41_descr = models.CharField(max_length=500,default='_')
    # E_41_brand = models.CharField(max_length=500,default='_')
    # E_41_qty = models.IntegerField()
    # E_42_name = models.CharField(max_length=500,default='_')
    # E_42_descr = models.CharField(max_length=500,default='_')
    # E_42_brand = models.CharField(max_length=500,default='_')
    # E_42_qty = models.IntegerField()
    # E_43_name = models.CharField(max_length=500,default='_')
    # E_43_descr = models.CharField(max_length=500,default='_')
    # E_43_brand = models.CharField(max_length=500,default='_')
    # E_43_qty = models.IntegerField()
    # E_44_name = models.CharField(max_length=500,default='_')
    # E_44_descr = models.CharField(max_length=500,default='_')
    # E_44_brand = models.CharField(max_length=500,default='_')
    # E_44_qty = models.IntegerField()
    # E_45_name = models.CharField(max_length=500,default='_')
    # E_45_descr = models.CharField(max_length=500,default='_')
    # E_45_brand = models.CharField(max_length=500,default='_')
    # E_45_qty = models.IntegerField()
    # E_46_name = models.CharField(max_length=500,default='_')
    # E_46_descr = models.CharField(max_length=500,default='_')
    # E_46_brand = models.CharField(max_length=500,default='_')
    # E_46_qty = models.IntegerField()
    # E_47_name = models.CharField(max_length=500,default='_')
    # E_47_descr = models.CharField(max_length=500,default='_')
    # E_47_brand = models.CharField(max_length=500,default='_')
    # E_47_qty = models.IntegerField()
    # E_48_name = models.CharField(max_length=500,default='_')
    # E_48_descr = models.CharField(max_length=500,default='_')
    # E_48_brand = models.CharField(max_length=500,default='_')
    # E_48_qty = models.IntegerField()
    # E_49_name = models.CharField(max_length=500,default='_')
    # E_49_descr = models.CharField(max_length=500,default='_')
    # E_49_brand = models.CharField(max_length=500,default='_')
    # E_49_qty = models.IntegerField()
    # E_50_name = models.CharField(max_length=500,default='_')
    # E_50_descr = models.CharField(max_length=500,default='_')
    # E_50_brand = models.CharField(max_length=500,default='_')
    # E_50_qty = models.IntegerField()
    # E_51_name = models.CharField(max_length=500,default='_')
    # E_51_descr = models.CharField(max_length=500,default='_')
    # E_51_brand = models.CharField(max_length=500,default='_')
    # E_51_qty = models.IntegerField()
    # E_52_name = models.CharField(max_length=500,default='_')
    # E_52_descr = models.CharField(max_length=500,default='_')
    # E_52_brand = models.CharField(max_length=500,default='_')
    # E_52_qty = models.IntegerField()
    # E_53_name = models.CharField(max_length=500,default='_')
    # E_53_descr = models.CharField(max_length=500,default='_')
    # E_53_brand = models.CharField(max_length=500,default='_')
    # E_53_qty = models.IntegerField()
    # E_54_name = models.CharField(max_length=500,default='_')
    # E_54_descr = models.CharField(max_length=500,default='_')
    # E_54_brand = models.CharField(max_length=500,default='_')
    # E_54_qty = models.IntegerField()
    # E_55_name = models.CharField(max_length=500,default='_')
    # E_55_descr = models.CharField(max_length=500,default='_')
    # E_55_brand = models.CharField(max_length=500,default='_')
    # E_55_qty = models.IntegerField()
    # E_56_name = models.CharField(max_length=500,default='_')
    # E_56_descr = models.CharField(max_length=500,default='_')
    # E_56_brand = models.CharField(max_length=500,default='_')
    # E_56_qty = models.IntegerField()

